# @package _global_
env_name: lunarlander_continuous_medium
agent_name: pg_ac  
run_id: ??? # decided during execution

train_episodes: 2000
gamma: 0.99
lr: 1e-4
batch_size: 100 #100
buffer_size: 1e6
