# @package _global_
env_name: bipedalwalker_easy #lunarlander_continuous_medium
agent_name: ppo

train_episodes: 5000
early_stop_episodes: 200
start_testing: 3000
test_interval: 25
gamma: 0.99 #0.95
lr: 0.0003
actor_hd: 256 #400
critic_hd: 256 #400

# ppo options
grad_clipping: 0.5
clip_eps: 0.2
entropy_weight: 0
num_agents: 1
horizon: 2000
num_minibathes: 10
minibatch_size: 64
gae_lambda: 0.95
