wandb_version: 1

_content:
  desc: null
  value:
    agent: pg_ac
    agent_name: pg_ac
    batch_size: '100'
    buffer_size: '1000000.0'
    env_name: bipedalwalker_easy
    exp_name: project_walker
    gamma: '0.99'
    lr: '0.0005'
    model_path: /m/home/home3/32/floreya1/unix/RL/rl_course/project/part1/results/bipedalwalker_easy/model/pg_ac_bipedalwalker_easy_params.pt
    run_id: '1668758484'
    run_suffix: '0'
    save_logging: 'True'
    save_model: 'True'
    save_video: 'True'
    seed: '1'
    silent: 'False'
    test_name: walk_pg_ac
    testing: 'False'
    train_episodes: '10000'
    use_wandb: 'True'
_flags_cache:
  desc: null
  value:
    allow_objects: null
    convert: null
    readonly: null
    struct: true
_metadata:
  desc: null
  value: 'ContainerMetadata(ref_type=typing.Any, object_type=<class ''dict''>, optional=True,
    key=None, flags={''struct'': True}, flags_root=False, resolver_cache=defaultdict(<class
    ''dict''>, {''now'': {(''%Y-%m-%d'',): ''2022-11-18'', (''%H-%M-%S'',): ''10-01-24''}}),
    key_type=typing.Any, element_type=typing.Any)'
_parent:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1668758486.904789
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.13.2
      8:
      - 5
